### ISSUE TITLE
[Sprint-7] DashBoard #BUG

### ISSUE THREAD

**Issue by Rhaijin** [datienza1991/oeas#116]
![Dashboard](https://user-images.githubusercontent.com/103364489/162616048-52fe0274-ac47-476c-997d-73e8955b3a4e.png)

Not clickable in the interface for the upcoming exam

**Comment by datienza1991** [comment]
Please indicate scenario what will happen after the card has been clicked for student and for faculty

**Comment by datienza1991** [comment]
added fix on #161
