### ISSUE TITLE
[Sprint-6] Examination #BUG

### ISSUE THREAD

**Issue by Rhaijin** [datienza1991/oeas#117]
If you take the examination, it will end automatically.
![Automatic](https://user-images.githubusercontent.com/103364489/162616436-8e17aa4b-f22f-4929-bbf7-70221a8792f6.png)
# #

**Comment by datienza1991** [comment]
Please check if the exam has questions. For adding question for a particular exam here is the screen shot.
![exam-add-question](https://user-images.githubusercontent.com/92292276/162659466-b0a35beb-73ee-47af-bc3b-b0fabb7854eb.gif)
